web/ujscert/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

import ujscert.vul.views as views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^submit$', views.submit_view, name='submit'),
    url(r'^upload$', views.upload_img),
    url(r'^about$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^top10$', views.rank_view, name='rank'),
    url(r'^legal$', TemplateView.as_view(template_name='legal.html'), name='legal'),

    url(r'^accounts/profile$', views.profile_view, name='profile'),
    url(r'^accounts/profile/edit$', views.update_profile_view, name='edit_profile'),
    url(r'^accounts/login/$', views.login_view, name='login'),
    url(r'^accounts/logout/$', views.logout_view, name='logout'),

    url(r'^profile/(?P<uid>\d+)$', views.profile_view, name='user_profile'),
    url(r'^detail/(?P<author>anonymous|member|all)/(?P<vid>\d+)$', views.detail_view, name='detail'),
    url(r'^comment/add/(?P<vid>\d+)', views.add_comment_view, name='add_comment'),
    url(r'^track/(?P<track_id>[0-9a-f]+)$', views.track_view, name='track'),

    url(r'^shop$', views.rewards_list_view, name='shop'),
    url(r'^shop/item/(?P<rid>\d+)', views.reward_detail_view, name='reward_detail'),

    url(r'^review/(?P<author>anonymous|member|all)/(?P<status>\d+|all)$', views.review_list_view, name='review'),
    url(r'^register/(?P<code>[0-9a-f]+)$', views.register_view, name='invite'),
    url(r'^register/successful$', TemplateView.as_view(template_name='register_successful.html'),
        name='register_successful'),

    url(r'^hq/', include('ujscert.headquarter.urls')),
    url(r'^captcha/', include('captcha.urls')),

    # 为隐藏后台, 可在 deploy_settings.py 中修改后台地址
    url(r'^%s/' % getattr(settings, 'ADMIN_PATH', 'admin'), admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/ujscert/vul/models.py
# coding=utf-8
from __future__ import unicode_literals

import hashlib
import os
import uuid
from datetime import datetime

from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Sum
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from django.forms import forms

STATUS_UNVERIFIED = 0
STATUS_CONFIRMED = 1
STATUS_IGNORED = 2
STATUS_TO_REVIEW = 3
STATUS_FIXED = 4
STATUS_OPEN = 5

STATUS_CHOICES = (
    (STATUS_UNVERIFIED, '待审核'),  # 漏洞已提交等待审核
    (STATUS_CONFIRMED, '已确认'),  # 漏洞已审核等待处理
    (STATUS_IGNORED, '已忽略'),  # 漏洞不符合要求, 不存在或者已知
    (STATUS_TO_REVIEW, '待复核'),  # 等待提交者复查
    (STATUS_FIXED, '已修复'),  # 修复完成
    (STATUS_OPEN, '已公开'),  # 社区可见
)

TIMELINE_CHANGE_STATUS = 0
TIMELINE_BOUNTY = 1

TIMELINE_CHOICES = (
    (TIMELINE_CHANGE_STATUS, '更新状态'),
    (TIMELINE_BOUNTY, '奖励变动'),
)


def attachment_name(instance, filename):
    date = datetime.now().strftime('%Y-%m-%d')
    name, ext = os.path.splitext(filename)
    new_name = instance.uuid + ext.lower()
    return os.path.join('uploads', date, new_name)


class Vul(models.Model):
    """漏洞"""
    title = models.CharField(max_length=32)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)  # 序列号
    category = models.IntegerField(choices=getattr(settings, 'VUL_TYPE_CHOICES'))
    anonymous = models.BooleanField(default=False)
    detail = models.TextField(max_length=2048)
    attachment = models.FileField(blank=True, upload_to=attachment_name)  # 附件

    status = models.IntegerField(choices=STATUS_CHOICES, default=0)  # 漏洞状态
    submitted = models.DateTimeField(auto_now_add=True, blank=True)  # 提交时间
    confirmed = models.DateTimeField(blank=True, null=True)  # 确认时间
    fixed = models.DateTimeField(blank=True, null=True)  # 修复时间
    score = models.IntegerField(blank=True, default=0,
                                validators=[MaxValueValidator(10), MinValueValidator(0)])  # 评分

    response = models.TextField(blank=True, max_length=512)  # 回复

    def __str__(self):
        return self.title


@receiver(post_save, sender=User)
def add_white_hat(sender, instance, **kwargs):
    if kwargs.get('created'):
        WhiteHat(user=instance).save()


@receiver(post_delete, sender=Vul)
def attachment_delete(sender, instance, **kwargs):
    instance.attachment.delete(False)


class WhiteHat(models.Model):
    """白帽子"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.CharField(max_length=100, blank=True, null=True)
    bio = models.CharField(max_length=200, blank=True, null=True)
    reputation = models.IntegerField(default=0)
    reports = models.IntegerField(default=0)
    site = models.CharField(max_length=100, default='http://', blank=True, null=True)
    public = models.BooleanField(default=False)

    @property
    def avatar(self):
        avatar_hash = hashlib.md5(self.user.email.lower().encode('utf8')).hexdigest()
        return "https://cn.gravatar.com/avatar/%s" % avatar_hash

    def __str__(self):
        return self.user.username


class AnonymousVul(Vul):
    ip = models.GenericIPAddressField()
    email = models.EmailField(blank=True, null=True)
    anonymous = True


class MemberVul(Vul):
    """会员提交漏洞"""
    author = models.ForeignKey(WhiteHat)
    anonymous = False


@receiver(post_delete, sender=MemberVul)
@receiver(post_save, sender=MemberVul)
def update_score(sender, instance, **kwargs):
    whitehat = WhiteHat.objects.get(pk=instance.author_id)
    vuls = MemberVul.objects.filter(author=whitehat)
    whitehat.reputation = vuls.aggregate(Sum('score')).get('score__sum')
    whitehat.reports = vuls.count()
    whitehat.save()


def image_name(instance, filename):
    date = datetime.now().strftime('%Y-%m-%d')
    name, ext = os.path.splitext(filename)
    filename = uuid.uuid1().hex + ext.lower()
    return os.path.join('images', date, filename)


class Image(models.Model):
    img = models.ImageField(upload_to=image_name)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True)

    def clean_img(self):
        image = self.cleaned_data.get('img')
        if not image:
            raise forms.ValidationError('图片不合法')

        main, sub = image.content_type.split('/')
        if not (main == 'image' and sub.lower() in ['jpeg', 'pjpeg', 'png', 'jpg']):
            raise forms.ValidationError('图片不合法')

        if len(image) > 1024 * 1024:  # max: 1M
            raise forms.ValidationError('文件尺寸太大')

        return image

    def __str__(self):
        return '%s (%d x %d)' % (self.img.path, self.img.width, self.img.height)


@receiver(post_delete, sender=Image)
def image_delete(sender, instance, **kwargs):
    instance.img.delete(False)


class Invitation(models.Model):
    """邀请码"""
    email = models.EmailField(blank=True, null=True)
    code = models.UUIDField(default=uuid.uuid4, editable=False)
    valid = models.BooleanField(default=True)
    expired = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.code, self.email)


class Timeline(models.Model):
    """事件"""
    vul = models.ForeignKey(Vul)
    event_type = models.IntegerField(choices=TIMELINE_CHOICES, default=TIMELINE_CHANGE_STATUS)
    extra = JSONField(default={})
    timestamp = models.DateTimeField(auto_created=True, auto_now_add=True)
    comment = models.CharField(max_length=1024)

    def __str__(self):
        return self.comment


class Comment(models.Model):
    author = models.ForeignKey(WhiteHat)
    vul = models.ForeignKey(Vul)
    timestamp = models.DateTimeField(auto_created=True, auto_now_add=True)
    content = models.CharField(max_length=1024)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return '%s: %s' % (self.author.user.username, self.content)


class LikeForComment(models.Model):
    author = models.ForeignKey(WhiteHat)
    timestamp = models.DateTimeField(auto_created=True, auto_now_add=True)
    comment = models.ForeignKey(Comment)

    def __str__(self):
        comment = self.comment.content
        max_len = 100
        if len(comment) > max_len:
            comment = comment[0:max_len] + '...'
        return '%s liked "%s"' % (self.author.user.username, comment)


class Income(models.Model):
    """积分变动"""
    user = models.ForeignKey(User)
    cost = models.IntegerField()  # 正为奖励, 负为消费
    reason = models.CharField(max_length=256)
    timestamp = models.DateTimeField(auto_created=True)

    def __str__(self):
        return '%s %d' % (self.user.username, self.cost)


class Reward(models.Model):
    title = models.CharField(max_length=64) # 名字
    intro = models.TextField(blank=True, max_length=200)  # 简介
    img = models.ImageField(upload_to=image_name, default='')  # 图片
    price = models.IntegerField()  # 售价
    purchased = models.IntegerField()  # 已兑换
    available = models.IntegerField()  # 余量

    def __str__(self):
        return self.title

web/templates/base.html
<!DOCTYPE html>
<html lang="zh-cn">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Security Response Center of Jiangsu University">
  <meta name="author" content="ChiChou">

  <title>{% block title %}江苏大学网络安全漏洞响应平台{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %} ">
  <link rel="stylesheet" href="{% static 'tether/dist/css/tether.min.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  {% block head %}{% endblock %}

</head>
<body>

<header id="top" class="navbar-dark navbar bg-inverse">
  <div class="container">
    <nav>
      <div class="nav navbar-nav dropdown pull-xs-right">
        {% if request.user.is_authenticated %}
          <button class="btn btn-primary-outline dropdown-toggle" type="button" id="user-dropdown"
                  data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
            <img src="{{ self_profile.avatar }}?s=20" class="avatar" width="20" height="20"> {{ request.user.username }}
          </button>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="user-dropdown">
            <a class="dropdown-item" href="{% url 'profile' %}">个人资料</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">退出</a>
          </div>

        {% else %}
          <a class="nav-item nav-link" href="{% url 'login' %}?next={{ request.path }}">登录</a>
        {% endif %}

      </div>

      <button class="navbar-toggler hidden-sm-up" type="button"
              data-toggle="collapse" data-target="#navbar">&#9776;</button>

      <div class="collapse navbar-toggleable-xs" id="navbar">

        <ul class="nav navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">首页</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-warning" href="{% url 'submit' %}">提交漏洞
              <sup><i class="fa fa-flash fa-fw"></i></sup></a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'rank' %}">英雄榜</a>
          </li>

          {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'review' status=0 author='all' %}">审核漏洞
                {% if to_be_review %}
                  <sup class="label label-danger label-pill">{{ to_be_review }}</sup>
                {% endif %}
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'search_home' %}">内网资产</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'alerts' %}">漏洞预警</a>
            </li>
          {% endif %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">关于</a>
          </li>
        </ul>

      </div>
    </nav>

  </div>
</header>


{% block body %}{% endblock %}

<footer class="bd-footer text-muted" role="contentinfo">
  <div class="container">
    <ul class="bd-footer-links">
      <li><a href="http://www.ujs.edu.cn">江苏大学</a></li>
      <li><a href="http://cs.ujs.edu.cn">计算机科学与通信工程学院</a></li>
    </ul>

    <p>&copy; 2016 <a href="http://metc.ujs.edu.cn">江苏大学信息化中心</a></p>
    <p>地址：江苏省镇江市学府路301号 邮编:212013</p>
  </div>
</footer>

<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'tether/dist/js/tether.min.js' %}"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
{% block scripts %}
{% endblock %}
</body>
</html>

web/templates/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}漏洞详情 - {{ vul.title }} {% endblock %}

{% block body %}
  <div class="container m-t-1">
    <ol class="breadcrumb">
      <li><a href="{% url 'home' %}">首页</a></li>
      <li class="active">漏洞详情</li>
    </ol>

    <div class="row">
      <div class="col-lg-12">
        <div class="container">
          <iframe name="if" class="hidden-xs-up"></iframe>
          <a href="?print" class="pull-right" target="if">打印整改通知</a>
          <h1 class="m-b-1"><span class="small">{{ vul.title }}</span></h1>
          <hr>
        </div>
      </div>

      <div class="col-md-7">
        <dl class="dl-horizontal m-l-0 m-r-0">
          <dt class="col-xs-4 col-md-2 text-truncate">提交时间</dt>
          <dd class="col-xs-8 col-md-4 text-truncate">{{ vul.submitted | date:"Y-m-d H:i" }}</dd>

          <dt class="col-xs-4 col-md-2 text-truncate">状态</dt>
          <dd class="col-xs-8 col-md-4 text-truncate">{% include 'mixins/status.html' %}</dd>

          <dt class="col-xs-4 col-md-2 text-truncate">确认时间</dt>
          <dd class="col-xs-8 col-md-4 text-truncate">{{ vul.confirmed | date:"Y-m-d H:i" | default:"暂未" }}</dd>

          <dt class="col-xs-4 col-md-2 text-truncate">修复时间</dt>
          <dd class="col-xs-8 col-md-4 text-truncate">{{ vul.fixed| date:"Y-m-d H:i" | default:"暂未" }}</dd>

          {% if is_anonymous %}
            <dt class="col-xs-4 col-md-2 text-truncate">来源 IP</dt>
            <dd class="col-xs-8 col-md-4 text-truncate">{{ vul.ip }}</dd>

            <dt class="col-xs-4 col-md-2 text-truncate">作者邮箱</dt>
            <dd class="col-xs-8 col-md-4 text-truncate">{{ vul.email | default:'无' }}</dd>

          {% else %}
            <dt class="col-xs-4 col-md-2 text-truncate">作者</dt>
            <dd class="col-xs-8 col-md-4 text-truncate">
              <a href="{% url 'user_profile' uid=vul.author.id %}">{{ vul.author }}</a></dd>

          {% endif %}
        </dl>

        <div class="container">
          <hr>
          <p><strong>漏洞详情:</strong></p>
          <pre data-render="markd">{{ vul.detail }}</pre>
          <hr>
          <p><strong>管理员答复:</strong></p>
          <p>{{ vul.response }}</p>
        </div>

        <div class="container">
          <hr>

          <ul class="comments list-unstyled">
            {% for comment in comments %}
              <li>
                <img src="{{ comment.author.avatar }}?s=40" class="avatar" width="40" height="40">
                <div class="content">
                  <header>
                    <a href="{% url 'user_profile' uid=comment.author.user.id %}">{{ comment.author.user.username }}</a>
                    <time>{{ comment.timestamp }}</time>
                  </header>
                  <p>{{ comment.content }}</p>
                </div>

              </li>
            {% empty %}
              暂无评论
            {% endfor %}
          </ul>

          <form id="comment-form" class="m-t-1" method="post" action="{% url 'add_comment' vid=vul.id %}">
            <fieldset class="form-group">
              {{ comment_form.response.errors }}
              <textarea class="form-control" cols="40" maxlength="512" name="content"
                        placeholder="发表自己的看法" rows="2"></textarea>

            </fieldset>

            <fieldset class="form-group row">
              <div class="col-sm-7 m-b-1">
                {{ comment_form.captcha }}
                <span class="invalid-captcha">验证码错误</span>
              </div>
              <div class="col-sm-5 text-md-right">
                <button type="submit" class="btn btn-success">评论</button>
              </div>
            </fieldset>

            {% csrf_token %}

          </form>

        </div>

      </div>

      <div class="col-md-5 hidden-print">
        <div class="events">
          <ul class="timeline list-unstyled">
            <li>
              <time>{{ vul.submitted }}</time>

              {% if is_anonymous %}
                匿名用户 {{ vul.email }}
              {% else %}
                用户 <a href="{% url 'user_profile' uid=vul.author.id %}">{{ vul.author }}</a>
              {% endif %}
              报告了此问题
            </li>
            {% for event in events %}
              <li>
                <time>{{ event.timestamp }}</time>
                漏洞状态变更为

                {% if event.extra.status == 1 %}
                  已确认
                {% elif event.extra.status == 2 %}
                  已忽略

                {% elif event.extra.status == 3 %}
                  等待复查

                {% elif event.extra.status == 4 %}
                  已修复

                {% elif event.extra.status == 5 %}
                  已公开

                {% endif %}

              </li>
            {% endfor %}
          </ul>
        </div>

        {% if user.is_superuser %}
          <div class="container">

            <form class="m-t-1" method="post">
              {{ form.non_field_errors }}

              <div class="m-b-1">
                {{ form.response.errors }}
                <label for="id_response">答复</label>
                <textarea class="form-control" cols="40" id="id_response" maxlength="512" name="response"
                          placeholder="漏洞的评价、致谢和修复方案" rows="6">{{ vul.response }}</textarea>

                <fieldset class="form-group">
                  {{ form.score.errors }}
                  <label for="id_score">评分</label>
                  <input type="number" name="score" min=0 max=10 class="form-control" id="id_score"
                         value="{{ vul.score }}" placeholder="评分">
                  <small class="text-muted">按照漏洞危害评分，从 1 到 10</small>
                </fieldset>

                <fieldset class="form-group">
                  {{ form.status.errors }}
                  <label for="id_status">状态</label>
                  <select name="status" id="id_status" class="form-control">
                    {% for i, label in status_choices %}
                      <option value="{{ i }}" {% if i == vul.status %}selected{% endif %}>{{ label }}</option>
                    {% endfor %}
                  </select>
                </fieldset>

                <fieldset class="form-group">
                  <button type="submit" class="btn btn-primary"><i
                      class="fa fa-check-circle-o"></i> 保存
                  </button>
                </fieldset>

              </div>

              {% csrf_token %}

            </form>
          </div>

        {% endif %}
      </div>

    </div>

  </div>
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="{% static 'js/markd.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/captcha.js' %}"></script>

  <script type="text/javascript">
    $(function () {
      var $form = $('#comment-form');
      $form.on('submit', function (e) {
        e.preventDefault();
        $.post($form.attr('action'), $form.serialize())
            .done(function () {
              location.reload()
            })
            .fail(function () {
              $form.find('.invalid-captcha').show();
              $form.find('textarea').focus();
            })
      })
    });
  </script>

{% endblock %}

web/templates/detail_print.html
<!DOCTYPE html>
<html lang="zh-cn">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Security Response Center of Jiangsu University">
  <meta name="author" content="ChiChou">

  <title>漏洞详情 - {{ vul.title }}</title>
  <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %} ">
  <link rel="stylesheet" href="{% static 'tether/dist/css/tether.min.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  {% block head %}{% endblock %}

</head>
<body>
  <div class="container m-t-1">
    <div class="row">
      <div class="col-lg-12">
        <div class="container">
          <h1 class="m-b-1"><span class="small">{{ vul.title }}</span></h1>
          <hr>
        </div>
      </div>

      <div class="col-lg-12">
        <dl class="dl-horizontal m-l-0 m-r-0">
          <dt class="col-xs-4 col-md-2 text-truncate">提交时间</dt>
          <dd class="col-xs-8 col-md-4 text-truncate">{{ vul.submitted | date:"Y-m-d H:i" }}</dd>

          <dt class="col-xs-4 col-md-2 text-truncate">状态</dt>
          <dd class="col-xs-8 col-md-4 text-truncate">{% include 'mixins/status.html' %}</dd>

          <dt class="col-xs-4 col-md-2 text-truncate">确认时间</dt>
          <dd class="col-xs-8 col-md-4 text-truncate">{{ vul.confirmed | date:"Y-m-d H:i" | default:"暂未" }}</dd>

          <dt class="col-xs-4 col-md-2 text-truncate">修复时间</dt>
          <dd class="col-xs-8 col-md-4 text-truncate">{{ vul.fixed| date:"Y-m-d H:i" | default:"暂未" }}</dd>

          {% if is_anonymous %}
            <dt class="col-xs-4 col-md-2 text-truncate">来源 IP</dt>
            <dd class="col-xs-8 col-md-4 text-truncate">{{ vul.ip }}</dd>

            <dt class="col-xs-4 col-md-2 text-truncate">作者邮箱</dt>
            <dd class="col-xs-8 col-md-4 text-truncate">{{ vul.email | default:'无' }}</dd>

          {% else %}
            <dt class="col-xs-4 col-md-2 text-truncate">作者</dt>
            <dd class="col-xs-8 col-md-4 text-truncate">
              <a href="{% url 'user_profile' uid=vul.author.id %}">{{ vul.author }}</a></dd>

          {% endif %}
        </dl>

        <div class="container">
          <hr>
          <p><strong>漏洞详情:</strong></p>
          <pre data-render="markd">{{ vul.detail }}</pre>
          <hr>
          <p><strong>管理员答复:</strong></p>
          <p>{{ vul.response }}</p>
        </div>

      </div>

    </div>

  </div>

  <script type="text/javascript" src="{% static 'js/markd.js' %}"></script>
  <script type="text/javascript">
    print();
    close();
  </script>

</body>
</html>

web/templates/edit_profile.html
{% extends 'base.html' %}

{% block body %}
  <div class="container m-t-2">
    <ol class="breadcrumb">
      <li><a href="{% url 'home' %}">首页</a></li>
      <li class="active">编辑个人资料</li>
    </ol>

    <div class="row">
      <div class="col-md-6 col-md-push-3">
        <form method="post">
          {{ form.as_p }}

          {% csrf_token %}

          <button class="btn btn-primary">保存资料</button>
        </form>
      </div>
    </div>

  </div>

{% endblock %}

web/templates/legal.html
{% extends 'base.html' %}

{% block title %}信息安全相关保护和声明{% endblock %}

{% block body %}
  <section class="jumbotron">
    <div class="container">
      <h1 class="jumbotron-heading">信息安全相关保护和声明</h1>
    </div>
  </section>

  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <p>对于在漏洞平台发布的漏洞，所有权归提交者所有。白帽子需要保证研究漏洞的方法、方式、工具及手段的合法性。</p>

        <p>在对校园网进行安全测试时必须遵守中华人民共和国相关法律法规的规定，用户应同意将不会利用本平台进行任何违法或不正当的活动，包括但不限于下列行为∶

        <p>一、上载、展示、张贴、传播或以其它方式传送含有下列内容之一的信息：</p>

        <ol>
          <li>反对宪法所确定的基本原则的；</li>
          <li>危害国家安全，泄露国家秘密，颠覆国家政权，破坏国家统一的；</li>
          <li>损害国家荣誉和利益的；</li>
          <li>煽动民族仇恨、民族歧视、破坏民族团结的；</li>
          <li>破坏国家宗教政策，宣扬邪教和封建迷信的；</li>
          <li>散布谣言，扰乱社会秩序，破坏社会稳定的；</li>
          <li>散布淫秽、色情、赌博、暴力、凶杀、恐怖或者教唆犯罪的；</li>
          <li>侮辱或者诽谤他人，侵害他人合法权利的；</li>
          <li>含有虚假、有害、胁迫、侵害他人隐私、骚扰、侵害、中伤、粗俗、猥亵、或其它道德上令人反感的内容；</li>
          <li>含有中国法律、法规、规章、条例以及任何具有法律效力之规范所限制或禁止的其它内容的；</li>
        </ol>

        <p>二、不得为任何非法目的而使用漏洞平台及漏洞平台提供的相关信息：</p>
        <ol>
          <li>不得利用漏洞平台进行任何可能对校园网正常运转造成不利影响的行为；</li>
          <li>不得利用漏洞平台提供的网络服务上传、展示或传播任何虚假的、骚扰性的、中伤他人的、辱骂性的、恐吓性的、庸俗淫秽的或其他任何非法的信息资料；</li>
          <li>不得侵犯其他任何第三方的专利权、著作权、商标权、名誉权或其他任何合法权益；</li>
        </ol>

        <p>三、不利用漏洞平台相关信息从事以下活动：</p>
        <ol>
          <li>未经允许，进入计算机信息网络或者使用计算机信息网络资源的；</li>
          <li>未经允许，对计算机信息网络功能进行删除、修改或者增加的；</li>
          <li>未经允许，对进入计算机信息网络中存储、处理或者传输的数据和应用程序进行删除、修改或者增加的；</li>
          <li>故意制作、传播计算机病毒等破坏性程序的；</li>
          <li>其他危害计算机信息网络安全的行为。</li>
        </ol>
      </div>


    </div>

  </div>
{% endblock body %}